#!/bin/sh
set -e

case "$1" in
    purge)
        rm -rf /var/lib/voidvault
        if getent passwd voidvault >/dev/null; then
            userdel voidvault || true
        fi
        if getent group voidvault >/dev/null; then
            groupdel voidvault || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
