#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent group voidvault >/dev/null; then
            groupadd --system voidvault
        fi

        if ! getent passwd voidvault >/dev/null; then
            useradd --system --gid voidvault --home-dir /var/lib/voidvault \
                --no-create-home --shell /usr/sbin/nologin \
                --comment "VoidVault Server Daemon" voidvault
        fi

        mkdir -p /var/lib/voidvault
        chown -R voidvault:voidvault /var/lib/voidvault
        chmod 700 /var/lib/voidvault
        ;;
esac

#DEBHELPER#

exit 0
